[package]
name = "sonarqube_mcp_server"
version = "0.0.8"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/sonarqube_mcp_server.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
schemars = "1.2.1"
zed_extension_api = "0.7.0"
