id = "mcp-server-sonarqube"
name = "SonarQube MCP Server"
version = "1.2.0"
schema_version = 1
authors = ["SonarSource <ide-marketplaces@sonarsource.com>"]
description = "SonarQube MCP Server that enables seamless integration with SonarQube Server or Cloud for code quality and security."
repository = "https://github.com/SonarSource/sonarqube-mcp-server"

[context_servers.mcp-server-sonarqube]
name = "SonarQube MCP Server"
description = "SonarQube MCP Server that enables seamless integration with SonarQube Server or Cloud for code quality and security."
